apiVersion: v2
actions:
  - name: "Run k6"
    events:
      - name: "sh.keptn.event.test.triggered"
    tasks:
      - name: "Run k6 with Keptn"
        files:
          - /files
        image: "golang"
        # cmd: ["sh"]
        # args: ["/keptn/files/execution.sh", "&&", "ls" ]
        cmd: ["go"]
        args: 
          - "install"
          - "go.k6.io/xk6/cmd/xk6@latest"
          - "&&"
          - "xk6"
          - "build"
          - "--with"
          - "github.com/mstoykov/xk6-counter@latest"