apiVersion: v2
actions:
  - name: "Run k6"
    events:
      - name: "sh.keptn.event.test.triggered"
    tasks:
      - name: "Run k6 with Keptn"
        files:
          - /files
        image: "loadimpact/k6"
        # cmd: ["sh"]
        # args: ["/keptn/files/execution.sh", "&&", "ls" ]
        cmd: ["ls"]
        args: ["/keptn/files/", "&&", "k6", "run", "--duration", "30s", "--vus", "10", "/keptn/files/k6_test.js"]